name: Test Workflow

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
      
    steps:
      - uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Clean project
        run: |
          rm -rf node_modules
          rm -f yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Build and run tests
        run: |
          yarn build
          yarn test
          